"""Threat Model CRUD + AI generation endpoints.

Threat models are generated by `services/threat_modeler.py` — this router
just persists the request, kicks off the background job, and serves
read/list/delete operations.

Versioning mirrors the scans pattern: rescanning a threat model creates a
new row with `parent_threat_model_id` pointing at the root of the chain.
"""
from __future__ import annotations
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from api.models.models import Client, FrameworkType, Project, Risk, RiskLevel, ThreatModel
from db.database import get_db
from core.security import get_current_user
from services.threat_modeler import (
    DEFAULT_METHODOLOGY, METHODOLOGIES, generate_threat_model_bg, methodology_catalog,
)


# Severity → (likelihood, impact, RiskLevel) for the threat→risk mapping.
# Keep the dimensions modest: a single high-severity threat shouldn't
# necessarily mean catastrophe — likelihood / impact get tuned in the
# Risk Register afterwards.
_SEV_TO_RISK: Dict[str, tuple[int, int, RiskLevel]] = {
    "critical": (5, 5, RiskLevel.CRITICAL),
    "high": (4, 4, RiskLevel.HIGH),
    "medium": (3, 3, RiskLevel.MEDIUM),
    "low": (2, 2, RiskLevel.LOW),
    "info": (1, 2, RiskLevel.LOW),
}

router = APIRouter(prefix="/clients/{client_id}/threat-models", tags=["threat-models"])

# Public methodology catalog — no client scoping, used by the create dialog.
methodology_router = APIRouter(prefix="/threat-models", tags=["threat-models"])


@methodology_router.get("/methodologies")
async def list_methodologies(_=Depends(get_current_user)):
    """Return the catalog of supported threat-modelling methodologies for
    the New Threat Model dialog's picker."""
    return {"methodologies": methodology_catalog(), "default": DEFAULT_METHODOLOGY}


@methodology_router.get("/library/{source}/{source_id}")
async def get_library_entry(
    source: str,
    source_id: str,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    """Look up a single threat-library entry. Powers the tooltip on a
    CAPEC / ATT&CK chip on the Threat Model detail page so the user can
    see what a reference actually means."""
    from api.models.models import ThreatLibrary
    src = (source or "").lower()
    if src not in ("capec", "attack"):
        raise HTTPException(status_code=400, detail="source must be 'capec' or 'attack'")
    row = (
        db.query(ThreatLibrary)
        .filter(ThreatLibrary.source == src, ThreatLibrary.source_id == source_id)
        .first()
    )
    if not row:
        raise HTTPException(
            status_code=404,
            detail=f"{source_id} not in cache — run a Sync to refresh the threat library.",
        )
    return {
        "source": row.source,
        "source_id": row.source_id,
        "name": row.name,
        "description": row.description,
        "category": row.category,
        "severity_default": row.severity_default,
        "mitigation_hint": row.mitigation_hint,
        "related_cwes": row.related_cwes or [],
        "extra": row.extra or {},
    }


# ── Schemas ──────────────────────────────────────────────────────────────────


class ThreatModelCreate(BaseModel):
    name: Optional[str] = None
    scope_type: str = "client"   # client | project | asset
    scope_id: Optional[str] = None
    project_id: Optional[str] = None
    framework: Optional[FrameworkType] = None
    methodology: Optional[str] = None  # stride | pasta | linddun | mitre_attack | kill_chain


class ThreatModelSummary(BaseModel):
    id: str
    client_id: str
    project_id: Optional[str] = None
    name: Optional[str] = None
    scope_type: str
    scope_id: Optional[str] = None
    framework: Optional[str] = None
    methodology: str = "stride"
    status: str
    component_count: int
    threat_count: int
    mitigation_count: int
    created_at: Optional[datetime] = None
    generated_at: Optional[datetime] = None
    parent_threat_model_id: Optional[str] = None
    error_message: Optional[str] = None

    model_config = {"from_attributes": True}


class ThreatModelDetail(ThreatModelSummary):
    executive_summary: Optional[str] = None
    components: List[Dict[str, Any]] = []
    data_flows: List[Dict[str, Any]] = []
    threats: List[Dict[str, Any]] = []
    mitigations: List[Dict[str, Any]] = []
    dfd_mermaid: Optional[str] = None
    ai_provider: Optional[str] = None
    ai_model: Optional[str] = None
    tokens_used: int = 0
    # IDs of threats already converted to Risk Register entries — UI uses
    # this to grey out the per-row Convert button and tell the bulk action
    # how many threats are new vs. already converted.
    converted_threat_ids: List[str] = []


class ConvertResult(BaseModel):
    created: int
    skipped: int
    risk_ids: List[str] = []


def _summary_from(tm: ThreatModel) -> Dict[str, Any]:
    return {
        "id": tm.id,
        "client_id": tm.client_id,
        "project_id": tm.project_id,
        "name": tm.name,
        "scope_type": tm.scope_type or "client",
        "scope_id": tm.scope_id,
        "framework": tm.framework.value if hasattr(tm.framework, "value") else tm.framework,
        "methodology": tm.methodology or "stride",
        "status": tm.status or "pending",
        "component_count": len(tm.components_json or []),
        "threat_count": len(tm.threats_json or []),
        "mitigation_count": len(tm.mitigations_json or []),
        "created_at": tm.created_at,
        "generated_at": tm.generated_at,
        "parent_threat_model_id": tm.parent_threat_model_id,
        "error_message": tm.error_message,
    }


def _detail_from(tm: ThreatModel, db: Optional[Session] = None) -> Dict[str, Any]:
    converted: List[str] = []
    if db is not None:
        converted = [
            sid for (sid,) in db.query(Risk.source_threat_id)
            .filter(Risk.source_threat_model_id == tm.id, Risk.source_threat_id.isnot(None))
            .all()
        ]
    return {
        **_summary_from(tm),
        "executive_summary": tm.executive_summary,
        "components": tm.components_json or [],
        "data_flows": tm.data_flows_json or [],
        "threats": tm.threats_json or [],
        "mitigations": tm.mitigations_json or [],
        "dfd_mermaid": tm.dfd_mermaid,
        "ai_provider": tm.ai_provider,
        "ai_model": tm.ai_model,
        "tokens_used": tm.tokens_used or 0,
        "converted_threat_ids": converted,
    }


def _threat_to_risk(
    *,
    tm: ThreatModel,
    threat: Dict[str, Any],
    mitigations: List[Dict[str, Any]],
    user: dict,
) -> Risk:
    """Build a Risk ORM object from a single threat + its mitigations."""
    sev = (threat.get("severity") or "medium").lower()
    likelihood, impact, level = _SEV_TO_RISK.get(sev, _SEV_TO_RISK["medium"])

    desc_parts: List[str] = []
    if threat.get("rationale"):
        desc_parts.append(threat["rationale"])
    refs: List[str] = []
    for c in threat.get("capec_refs") or []:
        refs.append(str(c))
    for a in threat.get("attack_techniques") or []:
        refs.append(f"ATT&CK {a}")
    if refs:
        desc_parts.append("References: " + ", ".join(refs))
    if threat.get("evidence"):
        desc_parts.append(f"Evidence: {threat['evidence']}")
    desc_parts.append(
        f"Sourced from threat model · {tm.methodology or 'stride'} · threat {threat.get('id', '')}"
    )

    mit_lines: List[str] = []
    for m in mitigations:
        line = f"{m.get('id', '')}: {m.get('action', '')}".strip(": ")
        if m.get("control_id"):
            line += f" (control {m['control_id']})"
        mit_lines.append(line)

    return Risk(
        client_id=tm.client_id,
        title=(threat.get("title") or f"Threat {threat.get('id', '')}")[:500],
        description="\n\n".join(p for p in desc_parts if p),
        risk_level=level,
        likelihood=likelihood,
        impact=impact,
        risk_score=round(likelihood * impact / 2.5, 1),
        category=(threat.get("category") or "").replace("_", " ").title() or None,
        owner=user.get("upn") or user.get("preferred_username"),
        status="open",
        mitigation_plan="\n".join(mit_lines) if mit_lines else None,
        finding_ids=[],
        source_threat_model_id=tm.id,
        source_threat_id=str(threat.get("id") or ""),
    )


# ── Endpoints ────────────────────────────────────────────────────────────────


@router.post("/", response_model=ThreatModelSummary, status_code=201)
async def create_threat_model(
    client_id: str,
    payload: ThreatModelCreate,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
    user: dict = Depends(get_current_user),
):
    """Persist a pending threat model and kick off generation in the
    background. Poll `GET /clients/{cid}/threat-models/{id}` for status."""
    if not db.query(Client.id).filter(Client.id == client_id).first():
        raise HTTPException(status_code=404, detail="Client not found")

    proj_id = payload.project_id
    if proj_id and not db.query(Project.id).filter(Project.id == proj_id, Project.client_id == client_id).first():
        raise HTTPException(status_code=404, detail="Project not found for this client")

    methodology = (payload.methodology or DEFAULT_METHODOLOGY).lower()
    if methodology not in METHODOLOGIES:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown methodology '{methodology}'. Pick one of: {', '.join(METHODOLOGIES)}",
        )
    tm = ThreatModel(
        client_id=client_id,
        project_id=proj_id,
        name=(payload.name or "").strip() or None,
        scope_type=payload.scope_type or "client",
        scope_id=payload.scope_id,
        framework=payload.framework,
        methodology=methodology,
        status="pending",
        initiated_by=user.get("upn", user.get("preferred_username", "system")),
    )
    db.add(tm)
    db.commit()
    db.refresh(tm)
    background_tasks.add_task(generate_threat_model_bg, tm.id)
    return _summary_from(tm)


@router.get("/", response_model=List[ThreatModelSummary])
async def list_threat_models(
    client_id: str,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    rows = (
        db.query(ThreatModel)
        .filter(ThreatModel.client_id == client_id)
        .order_by(ThreatModel.created_at.desc())
        .limit(200)
        .all()
    )
    # Collapse rescans: only the newest per (parent_threat_model_id ?? id).
    seen: set = set()
    out: List[Dict[str, Any]] = []
    rows_sorted = sorted(rows, key=lambda r: r.created_at or datetime.min, reverse=True)
    for r in rows_sorted:
        root = r.parent_threat_model_id or r.id
        if root in seen:
            continue
        seen.add(root)
        out.append(_summary_from(r))
    return out


@router.get("/{model_id}", response_model=ThreatModelDetail)
async def get_threat_model(
    client_id: str,
    model_id: str,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")
    return _detail_from(tm, db=db)


@router.get("/{model_id}/versions", response_model=List[ThreatModelSummary])
async def list_versions(
    client_id: str,
    model_id: str,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")
    root = tm.parent_threat_model_id or tm.id
    siblings = (
        db.query(ThreatModel)
        .filter(ThreatModel.client_id == client_id)
        .filter((ThreatModel.id == root) | (ThreatModel.parent_threat_model_id == root))
        .order_by(ThreatModel.created_at.desc())
        .all()
    )
    return [_summary_from(s) for s in siblings]


@router.post("/{model_id}/rescan", response_model=ThreatModelSummary, status_code=201)
async def rescan(
    client_id: str,
    model_id: str,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
    user: dict = Depends(get_current_user),
):
    """Generate a new version of an existing threat model. Same scope +
    framework as the original; new row links via parent_threat_model_id."""
    original = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not original:
        raise HTTPException(status_code=404, detail="Threat model not found")
    root = original.parent_threat_model_id or original.id
    new = ThreatModel(
        client_id=client_id,
        project_id=original.project_id,
        name=original.name,
        scope_type=original.scope_type,
        scope_id=original.scope_id,
        framework=original.framework,
        methodology=original.methodology or DEFAULT_METHODOLOGY,
        status="pending",
        initiated_by=user.get("upn", user.get("preferred_username", "system")),
        parent_threat_model_id=root,
    )
    db.add(new)
    db.commit()
    db.refresh(new)
    background_tasks.add_task(generate_threat_model_bg, new.id)
    return _summary_from(new)


@router.post("/{model_id}/threats/{threat_id}/convert-to-risk", status_code=201)
async def convert_threat_to_risk(
    client_id: str,
    model_id: str,
    threat_id: str,
    db: Session = Depends(get_db),
    user: dict = Depends(get_current_user),
):
    """Create a Risk Register entry from a single threat in this model.

    Idempotent: if a Risk already exists for (model_id, threat_id), return
    the existing one with 200 instead of 201."""
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")

    existing = (
        db.query(Risk)
        .filter(Risk.source_threat_model_id == tm.id, Risk.source_threat_id == threat_id)
        .first()
    )
    if existing:
        return {"risk_id": existing.id, "created": False}

    threats = tm.threats_json or []
    threat = next((t for t in threats if str(t.get("id")) == threat_id), None)
    if not threat:
        raise HTTPException(status_code=404, detail=f"Threat {threat_id} not in model")

    mitigations = [m for m in (tm.mitigations_json or []) if str(m.get("threat_id")) == threat_id]
    risk = _threat_to_risk(tm=tm, threat=threat, mitigations=mitigations, user=user)
    db.add(risk)
    db.commit()
    db.refresh(risk)
    return {"risk_id": risk.id, "created": True}


@router.post("/{model_id}/convert-all-to-risks", response_model=ConvertResult)
async def convert_all_threats_to_risks(
    client_id: str,
    model_id: str,
    db: Session = Depends(get_db),
    user: dict = Depends(get_current_user),
):
    """Bulk-convert every threat in the model to Risk Register entries,
    skipping any that already have a Risk for this (model_id, threat_id)."""
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")

    already = {
        sid for (sid,) in db.query(Risk.source_threat_id)
        .filter(Risk.source_threat_model_id == tm.id, Risk.source_threat_id.isnot(None))
        .all()
    }
    mitigations_by_threat: Dict[str, List[Dict[str, Any]]] = {}
    for m in tm.mitigations_json or []:
        mitigations_by_threat.setdefault(str(m.get("threat_id")), []).append(m)

    created_ids: List[str] = []
    skipped = 0
    for threat in tm.threats_json or []:
        tid = str(threat.get("id") or "")
        if not tid:
            skipped += 1
            continue
        if tid in already:
            skipped += 1
            continue
        risk = _threat_to_risk(
            tm=tm, threat=threat, mitigations=mitigations_by_threat.get(tid, []), user=user,
        )
        db.add(risk)
        db.flush()
        created_ids.append(risk.id)
    db.commit()
    return ConvertResult(created=len(created_ids), skipped=skipped, risk_ids=created_ids)


@router.delete("/{model_id}", status_code=204)
async def delete_threat_model(
    client_id: str,
    model_id: str,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")
    db.delete(tm)
    db.commit()
