"""Threat Model CRUD + AI generation endpoints.

Threat models are generated by `services/threat_modeler.py` — this router
just persists the request, kicks off the background job, and serves
read/list/delete operations.

Versioning mirrors the scans pattern: rescanning a threat model creates a
new row with `parent_threat_model_id` pointing at the root of the chain.
"""
from __future__ import annotations
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, BackgroundTasks, Depends, File, Form, HTTPException, UploadFile
from fastapi.responses import Response
from pydantic import BaseModel
from sqlalchemy.orm import Session

from api.models.models import Client, FrameworkType, Project, Risk, RiskLevel, ThreatModel
from db.database import get_db
from core.security import get_current_user
from services.diagram_extractor import SUPPORTED_EXTENSIONS, extract as extract_diagram
from services.drawio_renderer import render_drawio_xml
from services.threat_modeler import (
    DEFAULT_METHODOLOGY, METHODOLOGIES, generate_threat_model_bg, methodology_catalog,
)

# Max upload size for diagram files. PDFs can be big with embedded fonts;
# images we expect to be small. 10 MB is plenty for any reasonable
# architecture diagram and protects the API from accidental abuse.
_MAX_UPLOAD_BYTES = 10 * 1024 * 1024


# Severity → (likelihood, impact, RiskLevel) for the threat→risk mapping.
# Keep the dimensions modest: a single high-severity threat shouldn't
# necessarily mean catastrophe — likelihood / impact get tuned in the
# Risk Register afterwards.
_SEV_TO_RISK: Dict[str, tuple[int, int, RiskLevel]] = {
    "critical": (5, 5, RiskLevel.CRITICAL),
    "high": (4, 4, RiskLevel.HIGH),
    "medium": (3, 3, RiskLevel.MEDIUM),
    "low": (2, 2, RiskLevel.LOW),
    "info": (1, 2, RiskLevel.LOW),
}

router = APIRouter(prefix="/clients/{client_id}/threat-models", tags=["threat-models"])

# Public methodology catalog — no client scoping, used by the create dialog.
methodology_router = APIRouter(prefix="/threat-models", tags=["threat-models"])


@methodology_router.get("/methodologies")
async def list_methodologies(_=Depends(get_current_user)):
    """Return the catalog of supported threat-modelling methodologies for
    the New Threat Model dialog's picker."""
    return {"methodologies": methodology_catalog(), "default": DEFAULT_METHODOLOGY}


@methodology_router.get("/library/{source}/{source_id}")
async def get_library_entry(
    source: str,
    source_id: str,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    """Look up a single threat-library entry. Powers the tooltip on a
    CAPEC / ATT&CK chip on the Threat Model detail page so the user can
    see what a reference actually means."""
    from api.models.models import ThreatLibrary
    src = (source or "").lower()
    if src not in ("capec", "attack"):
        raise HTTPException(status_code=400, detail="source must be 'capec' or 'attack'")
    row = (
        db.query(ThreatLibrary)
        .filter(ThreatLibrary.source == src, ThreatLibrary.source_id == source_id)
        .first()
    )
    if not row:
        raise HTTPException(
            status_code=404,
            detail=f"{source_id} not in cache — run a Sync to refresh the threat library.",
        )
    return {
        "source": row.source,
        "source_id": row.source_id,
        "name": row.name,
        "description": row.description,
        "category": row.category,
        "severity_default": row.severity_default,
        "mitigation_hint": row.mitigation_hint,
        "related_cwes": row.related_cwes or [],
        "extra": row.extra or {},
    }


# ── Schemas ──────────────────────────────────────────────────────────────────


class ThreatModelCreate(BaseModel):
    name: Optional[str] = None
    scope_type: str = "client"   # client | project | asset
    scope_id: Optional[str] = None
    project_id: Optional[str] = None
    framework: Optional[FrameworkType] = None
    methodology: Optional[str] = None  # stride | pasta | linddun | mitre_attack | kill_chain


class ThreatModelSummary(BaseModel):
    id: str
    client_id: str
    project_id: Optional[str] = None
    name: Optional[str] = None
    scope_type: str
    scope_id: Optional[str] = None
    framework: Optional[str] = None
    methodology: str = "stride"
    status: str
    component_count: int
    threat_count: int
    mitigation_count: int
    created_at: Optional[datetime] = None
    generated_at: Optional[datetime] = None
    parent_threat_model_id: Optional[str] = None
    error_message: Optional[str] = None

    model_config = {"from_attributes": True}


class ThreatModelDetail(ThreatModelSummary):
    executive_summary: Optional[str] = None
    components: List[Dict[str, Any]] = []
    data_flows: List[Dict[str, Any]] = []
    threats: List[Dict[str, Any]] = []
    mitigations: List[Dict[str, Any]] = []
    dfd_mermaid: Optional[str] = None
    ai_provider: Optional[str] = None
    ai_model: Optional[str] = None
    tokens_used: int = 0
    # IDs of threats already converted to Risk Register entries — UI uses
    # this to grey out the per-row Convert button and tell the bulk action
    # how many threats are new vs. already converted.
    converted_threat_ids: List[str] = []
    # Phase 8 — completeness + coverage fields
    trust_boundaries: List[Dict[str, Any]] = []
    entry_points: List[Dict[str, Any]] = []
    coverage_decisions: List[Dict[str, Any]] = []
    maturity_scores: Dict[str, float] = {}


class ConvertResult(BaseModel):
    created: int
    skipped: int
    risk_ids: List[str] = []


def _summary_from(tm: ThreatModel) -> Dict[str, Any]:
    return {
        "id": tm.id,
        "client_id": tm.client_id,
        "project_id": tm.project_id,
        "name": tm.name,
        "scope_type": tm.scope_type or "client",
        "scope_id": tm.scope_id,
        "framework": tm.framework.value if hasattr(tm.framework, "value") else tm.framework,
        "methodology": tm.methodology or "stride",
        "status": tm.status or "pending",
        "component_count": len(tm.components_json or []),
        "threat_count": len(tm.threats_json or []),
        "mitigation_count": len(tm.mitigations_json or []),
        "created_at": tm.created_at,
        "generated_at": tm.generated_at,
        "parent_threat_model_id": tm.parent_threat_model_id,
        "error_message": tm.error_message,
    }


def _detail_from(tm: ThreatModel, db: Optional[Session] = None) -> Dict[str, Any]:
    converted: List[str] = []
    if db is not None:
        converted = [
            sid for (sid,) in db.query(Risk.source_threat_id)
            .filter(Risk.source_threat_model_id == tm.id, Risk.source_threat_id.isnot(None))
            .all()
        ]
    return {
        **_summary_from(tm),
        "executive_summary": tm.executive_summary,
        "components": tm.components_json or [],
        "data_flows": tm.data_flows_json or [],
        "threats": tm.threats_json or [],
        "mitigations": tm.mitigations_json or [],
        "dfd_mermaid": tm.dfd_mermaid,
        "ai_provider": tm.ai_provider,
        "ai_model": tm.ai_model,
        "tokens_used": tm.tokens_used or 0,
        "converted_threat_ids": converted,
        # Phase 8 — completeness + coverage
        "trust_boundaries": tm.trust_boundaries_json or [],
        "entry_points": tm.entry_points_json or [],
        "coverage_decisions": tm.coverage_decisions or [],
        "maturity_scores": tm.maturity_scores or {},
    }


def _threat_to_risk(
    *,
    tm: ThreatModel,
    threat: Dict[str, Any],
    mitigations: List[Dict[str, Any]],
    user: dict,
) -> Risk:
    """Build a Risk ORM object from a single threat + its mitigations."""
    sev = (threat.get("severity") or "medium").lower()
    likelihood, impact, level = _SEV_TO_RISK.get(sev, _SEV_TO_RISK["medium"])

    desc_parts: List[str] = []
    if threat.get("rationale"):
        desc_parts.append(threat["rationale"])
    refs: List[str] = []
    for c in threat.get("capec_refs") or []:
        refs.append(str(c))
    for a in threat.get("attack_techniques") or []:
        refs.append(f"ATT&CK {a}")
    if refs:
        desc_parts.append("References: " + ", ".join(refs))
    if threat.get("evidence"):
        desc_parts.append(f"Evidence: {threat['evidence']}")
    desc_parts.append(
        f"Sourced from threat model · {tm.methodology or 'stride'} · threat {threat.get('id', '')}"
    )

    mit_lines: List[str] = []
    for m in mitigations:
        line = f"{m.get('id', '')}: {m.get('action', '')}".strip(": ")
        if m.get("control_id"):
            line += f" (control {m['control_id']})"
        mit_lines.append(line)

    return Risk(
        client_id=tm.client_id,
        title=(threat.get("title") or f"Threat {threat.get('id', '')}")[:500],
        description="\n\n".join(p for p in desc_parts if p),
        risk_level=level,
        likelihood=likelihood,
        impact=impact,
        risk_score=round(likelihood * impact / 2.5, 1),
        category=(threat.get("category") or "").replace("_", " ").title() or None,
        owner=user.get("upn") or user.get("preferred_username"),
        status="open",
        mitigation_plan="\n".join(mit_lines) if mit_lines else None,
        finding_ids=[],
        source_threat_model_id=tm.id,
        source_threat_id=str(threat.get("id") or ""),
    )


# ── Endpoints ────────────────────────────────────────────────────────────────


@router.post("/", response_model=ThreatModelSummary, status_code=201)
async def create_threat_model(
    client_id: str,
    payload: ThreatModelCreate,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
    user: dict = Depends(get_current_user),
):
    """Persist a pending threat model and kick off generation in the
    background. Poll `GET /clients/{cid}/threat-models/{id}` for status."""
    if not db.query(Client.id).filter(Client.id == client_id).first():
        raise HTTPException(status_code=404, detail="Client not found")

    proj_id = payload.project_id
    if proj_id and not db.query(Project.id).filter(Project.id == proj_id, Project.client_id == client_id).first():
        raise HTTPException(status_code=404, detail="Project not found for this client")

    methodology = (payload.methodology or DEFAULT_METHODOLOGY).lower()
    if methodology not in METHODOLOGIES:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown methodology '{methodology}'. Pick one of: {', '.join(METHODOLOGIES)}",
        )
    tm = ThreatModel(
        client_id=client_id,
        project_id=proj_id,
        name=(payload.name or "").strip() or None,
        scope_type=payload.scope_type or "client",
        scope_id=payload.scope_id,
        framework=payload.framework,
        methodology=methodology,
        status="pending",
        initiated_by=user.get("upn", user.get("preferred_username", "system")),
    )
    db.add(tm)
    db.commit()
    db.refresh(tm)
    background_tasks.add_task(generate_threat_model_bg, tm.id)
    return _summary_from(tm)


@router.get("/", response_model=List[ThreatModelSummary])
async def list_threat_models(
    client_id: str,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    rows = (
        db.query(ThreatModel)
        .filter(ThreatModel.client_id == client_id)
        .order_by(ThreatModel.created_at.desc())
        .limit(200)
        .all()
    )
    # Collapse rescans: only the newest per (parent_threat_model_id ?? id).
    seen: set = set()
    out: List[Dict[str, Any]] = []
    rows_sorted = sorted(rows, key=lambda r: r.created_at or datetime.min, reverse=True)
    for r in rows_sorted:
        root = r.parent_threat_model_id or r.id
        if root in seen:
            continue
        seen.add(root)
        out.append(_summary_from(r))
    return out


@router.get("/{model_id}", response_model=ThreatModelDetail)
async def get_threat_model(
    client_id: str,
    model_id: str,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")
    return _detail_from(tm, db=db)


@router.get("/{model_id}/versions", response_model=List[ThreatModelSummary])
async def list_versions(
    client_id: str,
    model_id: str,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")
    root = tm.parent_threat_model_id or tm.id
    siblings = (
        db.query(ThreatModel)
        .filter(ThreatModel.client_id == client_id)
        .filter((ThreatModel.id == root) | (ThreatModel.parent_threat_model_id == root))
        .order_by(ThreatModel.created_at.desc())
        .all()
    )
    return [_summary_from(s) for s in siblings]


@router.post("/{model_id}/rescan", response_model=ThreatModelSummary, status_code=201)
async def rescan(
    client_id: str,
    model_id: str,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
    user: dict = Depends(get_current_user),
):
    """Generate a new version of an existing threat model. Same scope +
    framework as the original; new row links via parent_threat_model_id."""
    original = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not original:
        raise HTTPException(status_code=404, detail="Threat model not found")
    root = original.parent_threat_model_id or original.id
    new = ThreatModel(
        client_id=client_id,
        project_id=original.project_id,
        name=original.name,
        scope_type=original.scope_type,
        scope_id=original.scope_id,
        framework=original.framework,
        methodology=original.methodology or DEFAULT_METHODOLOGY,
        status="pending",
        initiated_by=user.get("upn", user.get("preferred_username", "system")),
        parent_threat_model_id=root,
    )
    db.add(new)
    db.commit()
    db.refresh(new)
    background_tasks.add_task(generate_threat_model_bg, new.id)
    return _summary_from(new)


@router.post("/{model_id}/threats/{threat_id}/convert-to-risk", status_code=201)
async def convert_threat_to_risk(
    client_id: str,
    model_id: str,
    threat_id: str,
    db: Session = Depends(get_db),
    user: dict = Depends(get_current_user),
):
    """Create a Risk Register entry from a single threat in this model.

    Idempotent: if a Risk already exists for (model_id, threat_id), return
    the existing one with 200 instead of 201."""
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")

    existing = (
        db.query(Risk)
        .filter(Risk.source_threat_model_id == tm.id, Risk.source_threat_id == threat_id)
        .first()
    )
    if existing:
        return {"risk_id": existing.id, "created": False}

    threats = tm.threats_json or []
    threat = next((t for t in threats if str(t.get("id")) == threat_id), None)
    if not threat:
        raise HTTPException(status_code=404, detail=f"Threat {threat_id} not in model")

    mitigations = [m for m in (tm.mitigations_json or []) if str(m.get("threat_id")) == threat_id]
    risk = _threat_to_risk(tm=tm, threat=threat, mitigations=mitigations, user=user)
    db.add(risk)
    db.commit()
    db.refresh(risk)
    return {"risk_id": risk.id, "created": True}


@router.post("/{model_id}/convert-all-to-risks", response_model=ConvertResult)
async def convert_all_threats_to_risks(
    client_id: str,
    model_id: str,
    db: Session = Depends(get_db),
    user: dict = Depends(get_current_user),
):
    """Bulk-convert every threat in the model to Risk Register entries,
    skipping any that already have a Risk for this (model_id, threat_id)."""
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")

    already = {
        sid for (sid,) in db.query(Risk.source_threat_id)
        .filter(Risk.source_threat_model_id == tm.id, Risk.source_threat_id.isnot(None))
        .all()
    }
    mitigations_by_threat: Dict[str, List[Dict[str, Any]]] = {}
    for m in tm.mitigations_json or []:
        mitigations_by_threat.setdefault(str(m.get("threat_id")), []).append(m)

    created_ids: List[str] = []
    skipped = 0
    for threat in tm.threats_json or []:
        tid = str(threat.get("id") or "")
        if not tid:
            skipped += 1
            continue
        if tid in already:
            skipped += 1
            continue
        risk = _threat_to_risk(
            tm=tm, threat=threat, mitigations=mitigations_by_threat.get(tid, []), user=user,
        )
        db.add(risk)
        db.flush()
        created_ids.append(risk.id)
    db.commit()
    return ConvertResult(created=len(created_ids), skipped=skipped, risk_ids=created_ids)


@router.get("/{model_id}/drawio")
async def get_threat_model_drawio(
    client_id: str,
    model_id: str,
    download: int = 0,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    """Render this threat model's DFD as draw.io / mxGraph XML.

    - `?download=1` returns the XML as a `.drawio` attachment, ready to
      open in draw.io desktop or diagrams.net.
    - default returns JSON `{xml, filename}` so the embedded viewer in
      the frontend can postMessage the XML into the diagrams.net iframe.
    """
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")

    title = tm.name or f"Threat Model {tm.id[:8]}"
    xml = render_drawio_xml(
        title=title,
        components=tm.components_json or [],
        data_flows=tm.data_flows_json or [],
        executive_summary=tm.executive_summary,
    )
    safe_name = "".join(c if c.isalnum() or c in "-_" else "-" for c in title)[:80] or "threat-model"
    filename = f"{safe_name}.drawio"
    if download:
        return Response(
            content=xml,
            media_type="application/vnd.jgraph.mxfile",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )
    return {"xml": xml, "filename": filename}


class FromDiagramResponse(BaseModel):
    model_id: str
    components: List[Dict[str, Any]]
    data_flows: List[Dict[str, Any]]
    source: str
    warnings: List[str] = []


@router.post("/from-diagram", response_model=FromDiagramResponse, status_code=201)
async def create_from_diagram(
    client_id: str,
    file: UploadFile = File(...),
    project_id: Optional[str] = Form(None),
    name: Optional[str] = Form(None),
    framework: Optional[str] = Form(None),
    methodology: Optional[str] = Form(None),
    db: Session = Depends(get_db),
    user: dict = Depends(get_current_user),
):
    """Upload an architecture diagram (.drawio / .xml / .pdf / .jpg / .png),
    extract components + data flows, and persist a ThreatModel row in
    `extracted_review` status.

    The user reviews / edits the extracted DFD on the detail page, then
    calls `POST /{id}/start-modeling` to kick off AI threat generation."""
    if not db.query(Client.id).filter(Client.id == client_id).first():
        raise HTTPException(status_code=404, detail="Client not found")
    if project_id and not db.query(Project.id).filter(
        Project.id == project_id, Project.client_id == client_id,
    ).first():
        raise HTTPException(status_code=404, detail="Project not found for this client")

    data = await file.read()
    if len(data) > _MAX_UPLOAD_BYTES:
        raise HTTPException(
            status_code=413,
            detail=f"File too large ({len(data)} bytes). Max {_MAX_UPLOAD_BYTES} bytes.",
        )
    if not data:
        raise HTTPException(status_code=400, detail="Empty file.")
    if not any((file.filename or "").lower().endswith(ext) for ext in SUPPORTED_EXTENSIONS):
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported file extension. Allowed: {sorted(SUPPORTED_EXTENSIONS)}",
        )

    try:
        extracted = await extract_diagram(file.filename or "", file.content_type, data)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except RuntimeError as exc:
        raise HTTPException(status_code=502, detail=str(exc))

    chosen_methodology = (methodology or DEFAULT_METHODOLOGY).lower()
    if chosen_methodology not in METHODOLOGIES:
        chosen_methodology = DEFAULT_METHODOLOGY
    chosen_framework: Optional[FrameworkType] = None
    if framework:
        try:
            chosen_framework = FrameworkType(framework)
        except ValueError:
            chosen_framework = None

    fallback_name = (file.filename or "Diagram upload").rsplit(".", 1)[0]
    tm = ThreatModel(
        client_id=client_id,
        project_id=project_id,
        name=(name or "").strip() or fallback_name[:200],
        scope_type="diagram",
        scope_id=None,
        framework=chosen_framework,
        methodology=chosen_methodology,
        status="extracted_review",
        initiated_by=user.get("upn", user.get("preferred_username", "system")),
        components_json=extracted["components"],
        data_flows_json=extracted["data_flows"],
        threats_json=[],
        mitigations_json=[],
        dfd_mermaid=None,
        executive_summary=(
            f"Diagram-derived architecture from uploaded {extracted['source']} "
            f"file `{file.filename}`. Pending AI threat analysis."
        ),
    )
    db.add(tm)
    db.commit()
    db.refresh(tm)
    return FromDiagramResponse(
        model_id=tm.id,
        components=extracted["components"],
        data_flows=extracted["data_flows"],
        source=extracted["source"],
        warnings=extracted.get("warnings", []),
    )


class ReviewedDfd(BaseModel):
    components: Optional[List[Dict[str, Any]]] = None
    data_flows: Optional[List[Dict[str, Any]]] = None
    name: Optional[str] = None
    framework: Optional[FrameworkType] = None
    methodology: Optional[str] = None


@router.post("/{model_id}/start-modeling", response_model=ThreatModelSummary, status_code=202)
async def start_modeling_from_diagram(
    client_id: str,
    model_id: str,
    payload: ReviewedDfd,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
    user: dict = Depends(get_current_user),
):
    """After the user has reviewed (and optionally edited) the
    diagram-extracted components and data flows, accept the reviewed
    payload and kick off AI threat generation on top of it."""
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")
    if tm.status != "extracted_review":
        raise HTTPException(
            status_code=409,
            detail=f"Cannot start modelling — status is '{tm.status}', expected 'extracted_review'.",
        )

    if payload.components is not None:
        tm.components_json = payload.components
    if payload.data_flows is not None:
        tm.data_flows_json = payload.data_flows
    if payload.name:
        tm.name = payload.name.strip()[:200] or tm.name
    if payload.framework is not None:
        tm.framework = payload.framework
    if payload.methodology:
        m = payload.methodology.lower()
        if m in METHODOLOGIES:
            tm.methodology = m
    tm.status = "pending"
    tm.initiated_by = user.get("upn", user.get("preferred_username", "system"))
    db.commit()
    db.refresh(tm)
    background_tasks.add_task(generate_threat_model_bg, tm.id)
    return _summary_from(tm)


# ── Phase 8 endpoints ───────────────────────────────────────────────────────


class ThreatPatch(BaseModel):
    """Inline edit for a single threat (Phase 8C workshop mode)."""
    status: Optional[str] = None
    decision_notes: Optional[str] = None
    residual_severity: Optional[str] = None
    residual_rationale: Optional[str] = None
    owner_role: Optional[str] = None


class MitigationPatch(BaseModel):
    status: Optional[str] = None
    implementation_detail: Optional[str] = None
    evidence_link: Optional[Dict[str, Any]] = None
    owner_role: Optional[str] = None


_VALID_THREAT_STATUS = {"identified", "mitigated", "accepted", "transferred", "compensated", "not_applicable"}
_VALID_OWNER_ROLES = {"security", "appdev", "platform", "grc"}
_VALID_SEV = {"critical", "high", "medium", "low"}


def _user_label(user: dict) -> str:
    return user.get("upn") or user.get("preferred_username") or user.get("email") or "system"


def _mark_modified(tm: ThreatModel, field: str) -> None:
    from sqlalchemy.orm.attributes import flag_modified
    flag_modified(tm, field)


@router.patch("/{model_id}/threats/{threat_id}")
async def patch_threat(
    client_id: str,
    model_id: str,
    threat_id: str,
    payload: ThreatPatch,
    db: Session = Depends(get_db),
    user: dict = Depends(get_current_user),
):
    """Workshop-mode inline edit for a single threat. Updates status,
    decision_notes, residual_severity/rationale, owner_role."""
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")
    threats = list(tm.threats_json or [])
    found = None
    for t in threats:
        if str(t.get("id")) == threat_id:
            found = t
            break
    if not found:
        raise HTTPException(status_code=404, detail=f"Threat {threat_id} not in model")
    changes = payload.model_dump(exclude_unset=True)
    if "status" in changes:
        s = (changes["status"] or "").lower()
        if s not in _VALID_THREAT_STATUS:
            raise HTTPException(status_code=400, detail=f"Invalid status. Valid: {sorted(_VALID_THREAT_STATUS)}")
        found["status"] = s
    if "decision_notes" in changes:
        found["decision_notes"] = str(changes["decision_notes"] or "")[:2000]
    if "residual_severity" in changes:
        s = (changes["residual_severity"] or "").lower()
        found["residual_severity"] = s if s in _VALID_SEV else None
    if "residual_rationale" in changes:
        found["residual_rationale"] = str(changes["residual_rationale"] or "")[:2000]
    if "owner_role" in changes:
        r = (changes["owner_role"] or "").lower()
        if r in _VALID_OWNER_ROLES:
            found["owner_role"] = r
    found["decided_by"] = _user_label(user)
    found["decided_at"] = datetime.now(timezone.utc).isoformat()
    tm.threats_json = threats
    _mark_modified(tm, "threats_json")
    db.commit()
    db.refresh(tm)
    return found


@router.patch("/{model_id}/mitigations/{mitigation_id}")
async def patch_mitigation(
    client_id: str,
    model_id: str,
    mitigation_id: str,
    payload: MitigationPatch,
    db: Session = Depends(get_db),
    _: dict = Depends(get_current_user),
):
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")
    mits = list(tm.mitigations_json or [])
    found = None
    for m in mits:
        if str(m.get("id")) == mitigation_id:
            found = m
            break
    if not found:
        raise HTTPException(status_code=404, detail=f"Mitigation {mitigation_id} not in model")
    changes = payload.model_dump(exclude_unset=True)
    if "status" in changes:
        found["status"] = str(changes["status"] or "open")
    if "implementation_detail" in changes:
        found["implementation_detail"] = str(changes["implementation_detail"] or "")[:5000]
    if "evidence_link" in changes:
        found["evidence_link"] = changes["evidence_link"]
    if "owner_role" in changes:
        r = (changes["owner_role"] or "").lower()
        if r in _VALID_OWNER_ROLES:
            found["owner_role"] = r
    tm.mitigations_json = mits
    _mark_modified(tm, "mitigations_json")
    db.commit()
    db.refresh(tm)
    return found


@router.get("/{model_id}/coverage")
async def get_coverage_matrix(
    client_id: str,
    model_id: str,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    """Phase 8B — coverage matrix endpoint. Returns the (component × category)
    grid plus completion stats. Used by the Coverage tab in the UI."""
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")
    decisions = tm.coverage_decisions or []
    components = tm.components_json or []
    threats_by_id = {str(t.get("id")): t for t in (tm.threats_json or [])}
    # Flat list keyed (component_id, category)
    matrix: Dict[str, Dict[str, Any]] = {}
    for d in decisions:
        key = f"{d.get('component_id')}|{d.get('category')}"
        matrix[key] = {
            "component_id": d.get("component_id"),
            "category": d.get("category"),
            "state": d.get("state"),
            "threat_id": d.get("threat_id"),
            "rationale": d.get("rationale"),
            "threat": threats_by_id.get(str(d.get("threat_id"))) if d.get("threat_id") else None,
        }
    total = len(decisions)
    threat_cells = sum(1 for d in decisions if d.get("state") == "threat")
    considered_cells = sum(1 for d in decisions if d.get("state") == "considered")
    na_cells = sum(1 for d in decisions if d.get("state") == "not_applicable")
    missing_cells = sum(1 for d in decisions if d.get("state") == "missing")
    coverage_pct = 0 if total == 0 else round(((total - missing_cells) / total) * 100, 1)
    return {
        "model_id": model_id,
        "methodology": tm.methodology,
        "components": components,
        "categories": _categories_for(tm.methodology or "stride"),
        "cells": list(matrix.values()),
        "stats": {
            "total_cells": total,
            "threat_cells": threat_cells,
            "considered_cells": considered_cells,
            "not_applicable_cells": na_cells,
            "missing_cells": missing_cells,
            "coverage_pct": coverage_pct,
        },
    }


def _categories_for(methodology: str) -> List[str]:
    from services.threat_modeler import METHODOLOGIES, DEFAULT_METHODOLOGY
    spec = METHODOLOGIES.get(methodology) or METHODOLOGIES[DEFAULT_METHODOLOGY]
    return list(spec["categories"])


@router.post("/{model_id}/coverage/fill-gaps")
async def fill_coverage_gaps(
    client_id: str,
    model_id: str,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    """Phase 8B — targeted LLM fill of every 'missing' cell in the coverage
    matrix. For each (component, category) gap, the LLM either:

      - emits a new threat (full Phase 8 shape) and the cell flips to 'threat'
      - emits a coverage decision (considered | not_applicable) with rationale

    Cells that already have state != 'missing' are left untouched. New threats
    are appended to threats_json; the coverage_decisions list is updated in
    place. Maturity scores are recomputed.

    Best-effort: errors surface to the caller; rows aren't half-updated."""
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")

    decisions = list(tm.coverage_decisions or [])
    missing = [d for d in decisions if d.get("state") == "missing"]
    if not missing:
        return {"filled": 0, "threats_added": 0, "decisions_updated": 0, "message": "Nothing missing"}

    try:
        from services.threat_modeler_gapfill import fill_gaps
        from services.maturity_scorer import compute_maturity_scores
        added_threats, updated_decisions = await fill_gaps(
            db=db, tm=tm, missing_cells=missing,
        )
    except RuntimeError as exc:
        raise HTTPException(status_code=502, detail=str(exc))

    # Merge: keep all non-missing decisions, replace missing ones with the
    # updated ones (matched by component_id + category).
    keep = {(d["component_id"], d["category"]): d for d in decisions if d.get("state") != "missing"}
    for d in updated_decisions:
        keep[(d["component_id"], d["category"])] = d
    new_decisions = list(keep.values())

    # Append new threats
    threats_list = list(tm.threats_json or [])
    threats_list.extend(added_threats)
    tm.threats_json = threats_list
    tm.coverage_decisions = new_decisions
    try:
        tm.maturity_scores = compute_maturity_scores(db, tm.client_id, tm.methodology or "stride", threats_list)
    except Exception:
        pass
    from sqlalchemy.orm.attributes import flag_modified
    flag_modified(tm, "threats_json")
    flag_modified(tm, "coverage_decisions")
    flag_modified(tm, "maturity_scores")
    db.commit()
    db.refresh(tm)
    return {
        "filled": len(updated_decisions),
        "threats_added": len(added_threats),
        "decisions_updated": len(updated_decisions),
        "message": f"Filled {len(updated_decisions)} cells ({len(added_threats)} new threats)",
    }


@router.get("/{model_id}/dfd")
async def get_dfd_styled(
    client_id: str,
    model_id: str,
    view: str = "architecture",
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    """Phase 9B — return the Mermaid DFD styled for a specific lens.

    view ∈ {architecture, threat_heat, detection_coverage}.

    For 'architecture' we just return the canonical dfd_mermaid; the
    other views append `style nodeId ...` + `linkStyle N ...` lines
    that overlay threat-severity heat or SOC detection-coverage colors.
    """
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")
    from services.dfd_styler import style_dfd, VIEWS
    v = (view or "architecture").lower()
    if v not in VIEWS:
        raise HTTPException(status_code=400, detail=f"Unknown view. Valid: {sorted(VIEWS)}")
    styled = style_dfd(
        view=v,
        base_mermaid=tm.dfd_mermaid or "",
        components=tm.components_json or [],
        data_flows=tm.data_flows_json or [],
        threats=tm.threats_json or [],
    )
    return {"view": v, "mermaid": styled}


@router.get("/{model_id}/maturity")
async def get_maturity(
    client_id: str,
    model_id: str,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    """Phase 8E — maturity scores + a summary. Recomputes on demand so a
    workshop edit (mitigated → score++) shows up immediately."""
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")
    from services.maturity_scorer import compute_maturity_scores, maturity_summary
    scores = compute_maturity_scores(db, tm.client_id, tm.methodology or "stride", tm.threats_json or [])
    tm.maturity_scores = scores
    _mark_modified(tm, "maturity_scores")
    db.commit()
    summary = maturity_summary(scores)
    return {"scores": scores, "summary": summary}


@router.get("/{model_id}/diff/{prev_id}")
async def diff_threat_models(
    client_id: str,
    model_id: str,
    prev_id: str,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    """Phase 8D — diff two threat models in the same chain. Returns
    {added, removed, severity_changed, status_changed} of threats."""
    a = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    b = db.query(ThreatModel).filter(
        ThreatModel.id == prev_id, ThreatModel.client_id == client_id,
    ).first()
    if not a or not b:
        raise HTTPException(status_code=404, detail="Threat model(s) not found")

    def key_for(t: Dict[str, Any]) -> str:
        # Match by (asset_id, category, title) — id changes on rescan.
        return f"{t.get('asset_id')}|{t.get('category')}|{str(t.get('title') or '').strip().lower()[:80]}"

    a_threats = {key_for(t): t for t in (a.threats_json or [])}
    b_threats = {key_for(t): t for t in (b.threats_json or [])}

    added = [a_threats[k] for k in a_threats.keys() - b_threats.keys()]
    removed = [b_threats[k] for k in b_threats.keys() - a_threats.keys()]
    severity_changed: List[Dict[str, Any]] = []
    status_changed: List[Dict[str, Any]] = []
    for k in a_threats.keys() & b_threats.keys():
        at, bt = a_threats[k], b_threats[k]
        if at.get("severity") != bt.get("severity"):
            severity_changed.append({
                "title": at.get("title"), "asset_id": at.get("asset_id"),
                "category": at.get("category"),
                "from": bt.get("severity"), "to": at.get("severity"),
            })
        if at.get("status") != bt.get("status"):
            status_changed.append({
                "title": at.get("title"), "asset_id": at.get("asset_id"),
                "category": at.get("category"),
                "from": bt.get("status"), "to": at.get("status"),
            })

    return {
        "current": {"id": a.id, "generated_at": a.generated_at.isoformat() if a.generated_at else None},
        "previous": {"id": b.id, "generated_at": b.generated_at.isoformat() if b.generated_at else None},
        "added": added,
        "removed": removed,
        "severity_changed": severity_changed,
        "status_changed": status_changed,
    }


@router.get("/{model_id}/pdf")
async def get_threat_model_pdf(
    client_id: str,
    model_id: str,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    """Phase 8F — server-rendered board-ready deliverable.

    Returns a standalone HTML document with print CSS embedded. The
    frontend opens it in a new tab and the user prints to PDF. This
    avoids the AppLayout shell / overflow issues that browser-print
    of the live page hits, and produces a deliverable-quality
    artifact without server-side native-PDF dependencies."""
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")
    client_name = "Unknown Client"
    c = db.query(Client).filter(Client.id == tm.client_id).first()
    if c:
        client_name = c.name
    from services.threat_model_pdf import render_threat_model_html
    html = render_threat_model_html(tm, client_name=client_name)
    return Response(content=html, media_type="text/html; charset=utf-8")


@router.delete("/{model_id}", status_code=204)
async def delete_threat_model(
    client_id: str,
    model_id: str,
    db: Session = Depends(get_db),
    _=Depends(get_current_user),
):
    tm = db.query(ThreatModel).filter(
        ThreatModel.id == model_id, ThreatModel.client_id == client_id,
    ).first()
    if not tm:
        raise HTTPException(status_code=404, detail="Threat model not found")
    db.delete(tm)
    db.commit()
